Implement fields in Player Class
Bazalii/School_Live_Simulator pull request #45
Opened 2021-08-11 10:46 UTC by yevGen-S

- setters for bicycle, guitar, computer - States
 - functions for Player work: playSong(),deliver(),realiseWebTask()
 - function for Player eat
 - functions to change 3 main stats of Player
 - functions to change States of items in Bag
 - Closes:#36

2021-08-11 15:00 UTC, Bazalii requested changes
Several things should be changed

2021-08-11 20:15 UTC, yevGen-S commented on Project_source/app/src/main/java/android/clicker/school_live_simulator/Classes/Main/Player.kt
>      object Bag {
Fixed

2021-08-11 20:15 UTC, yevGen-S commented on Project_source/app/src/main/java/android/clicker/school_live_simulator/Classes/Main/Player.kt
> +            addMoney(song)
Fixed

2021-08-11 20:15 UTC, yevGen-S commented on Project_source/app/src/main/java/android/clicker/school_live_simulator/Classes/Main/Player.kt
>  }
Fixed

2021-08-11 20:15 UTC, yevGen-S commented on Project_source/app/src/main/java/android/clicker/school_live_simulator/Classes/Main/Player.kt
> +                }
Fixed

2021-08-12 09:41 UTC, Bazalii approved these changes

2021-08-12 09:42 UTC, Endray952 approved these changes

2021-08-12 09:43 UTC, merged